name: insta_attend
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  download: ^1.0.0
  blurrycontainer: ^1.0.2
  art_sweetalert: ^0.0.5
  animated_text_kit: ^4.2.2
  flutter_animated_button: ^2.0.3
  loading_animation_widget: ^1.2.0+4
  universal_html: ^2.2.4
  lottie: ^3.0.0
  shared_preferences: ^2.2.2
  csv: ^5.1.1
  admonitions: ^1.0.1
  intl:
  flutter_slidable: ^3.0.1
  charts_flutter: ^0.12.0
  text_divider: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true
  assets:
     - assets/images/
     - assets/Lottie/

  # example:
  fonts:
     - family: Roman
       fonts:
         - asset: assets/fonts/Roman.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
     - family: Typewriter
       fonts:
         - asset: assets/fonts/AniTypewriter.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
